name: get_apps
description: Flutter Plugin to get all installed apps on android.
version: 1.0.8
homepage: https://github.com/TanmayMudgal619/get_apps

environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.get_apps
        pluginClass: GetAppsPlugin
